### PR TITLE
Add buttons to control how many systems are rendered at once

### PR DESCRIPTION
**Pull request by tankorsmash**
It was glitching out my browser to render all 8000 at once. This adds or removes 1000 from the max number of systems to render. Can't go lower than 10 and starts at 1000.

image

### CODE REVIEW

**Comment by wolfadex** [comment]
@tankorsmash sorry this is glitching out for you! I think this might be a little nicer in a settings panel. There are other things I know I will be including in there later as well. I have one partially setup already, let me hook it back up get this added in there.

**Comment by tankorsmash** [comment]
Oh cool yeah, a settings panel would be a much better place!

**Comment by wolfadex** [comment]
Ok, I've added a setting modal. Button is in the bottom left. If you'd be willing to refactor to use that for setting the limit I'd be happy to merge.

**Comment by tankorsmash** [comment]
I've updated the PR to use the new settings modal instead of the onscreen buttons.

I force pushed a commit to my branch, which may have caused the netlify build to choke. It's saying a resource is busy like you would if you recompiled too quickly. I don't have any experience with Netlify, so I'm not sure what the next step is for that.

**Comment by wolfadex** [comment]
Ok, I think I've gotten these into `main` now though through a separate commit. I'm still not sure what's going on with Netlify builds failing some times as I've never had this happen with other projects. The last build worked, but I'll keep an eye on the builds.

If there's anything still missing, please make another PR!

**Comment by tankorsmash** [comment]
Thanks for looking into this!

**Pull request closed without merging**
